# Generated by Django 5.0.4 on 2024-04-15 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('newsid', models.IntegerField(primary_key=True, serialize=False)),
                ('newstitle', models.CharField(max_length=255)),
                ('newscontent', models.TextField()),
                ('newsdate', models.CharField(max_length=255)),
                ('newsauthor', models.CharField(max_length=255)),
                ('cid', models.IntegerField()),
                ('newsimg', models.TextField()),
                ('cname', models.CharField(max_length=255)),
                ('seetimes', models.IntegerField()),
                ('timeliness', models.FloatField(default=100)),
                ('likenumbers', models.IntegerField()),
                ('commentnumbers', models.IntegerField()),
                ('collectionnumbers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Newstype',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=255)),
                ('passwd', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('img', models.TextField()),
                ('word', models.TextField()),
                ('usertype', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('likeid', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewsre.news')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collectionid', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewsre.news')),
            ],
        ),
        migrations.CreateModel(
            name='Newscomment',
            fields=[
                ('commentid', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewsre.news')),
            ],
        ),
        migrations.CreateModel(
            name='Newsrecommend',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255)),
                ('cid', models.IntegerField()),
                ('refire', models.FloatField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewsre.news')),
            ],
        ),
        migrations.CreateModel(
            name='Newssee',
            fields=[
                ('seeid', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255)),
                ('cid', models.IntegerField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewsre.news')),
            ],
        ),
    ]
