# Generated by Django 5.0.4 on 2024-04-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0002_news_newstype_user_like_collection_newscomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='collectionnumbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='commentnumbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='likenumbers',
            field=models.IntegerField(default=0),
        ),
    ]
