# Generated by Django 5.0.4 on 2024-04-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0003_alter_news_collectionnumbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='fire',
            field=models.FloatField(default=0),
        ),
    ]
