# Generated by Django 5.0.4 on 2024-04-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0005_remove_newssee_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
