# Generated by Django 5.0.4 on 2024-04-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0006_delete_userinfo_user_sex'),
    ]

    operations = [
    ]
