# Generated by Django 5.0.4 on 2024-04-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0007_img_delete_userinfo'),
    ]

    operations = [

    ]
