# Generated by Django 5.0.4 on 2024-04-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0008_delete_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssee',
            name='seetime',
            field=models.DateTimeField(max_length=255, null=True),
        ),
    ]
