# Generated by Django 5.0.4 on 2024-04-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0009_newssee_seetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomment',
            name='commenttime',
            field=models.DateTimeField(max_length=255, null=True),
        ),
    ]
