# Generated by Django 5.0.4 on 2024-04-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0010_img_delete_userinfo_newscomment_commenttime'),
    ]

    operations = [

        migrations.CreateModel(
            name='Userread',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255)),
                ('readtime', models.IntegerField()),
                ('readnumbers', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
