# Generated by Django 5.0.4 on 2024-04-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0011_img_userread_delete_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userread',
            name='readnumbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userread',
            name='readtime',
            field=models.IntegerField(default=0),
        ),
    ]
