# Generated by Django 5.0.4 on 2024-04-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0012_img_delete_userinfo_alter_userread_readnumbers_and_more'),
    ]

    operations = [

        migrations.CreateModel(
            name='Userclouds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255)),
                ('cloudword', models.CharField(max_length=255)),
                ('cloudtime', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
