# Generated by Django 5.0.4 on 2024-04-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0013_img_userclouds_delete_userinfo'),
    ]

    operations = [

        migrations.AddField(
            model_name='newstype',
            name='typeimg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='word',
            field=models.TextField(null=True),
        ),
    ]
