# Generated by Django 5.0.4 on 2024-04-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0014_img_delete_userinfo_newstype_typeimg_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='newstype',
            name='typeimg',
            field=models.TextField(null=True),
        ),
    ]
