# Generated by Django 5.0.4 on 2024-04-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0015_img_delete_userinfo_alter_newstype_typeimg'),
    ]

    operations = [

        migrations.AddField(
            model_name='newsrecommend',
            name='addfire',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='newsrecommend',
            name='basefire',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='newsrecommend',
            name='refire',
            field=models.FloatField(default=0),
        ),
    ]
