# Generated by Django 5.0.4 on 2024-04-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0016_img_delete_userinfo_newsrecommend_addfire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uservisit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
