# Generated by Django 5.0.4 on 2024-05-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0018_img_province_delete_userinfo_user_age_user_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsrecommend',
            name='cos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='seetimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='timeliness',
            field=models.IntegerField(default=100),
        ),
    ]
