# Generated by Django 5.0.4 on 2024-05-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0019_img_delete_userinfo_newsrecommend_cos_and_more'),
    ]

    operations = [

    ]
