# Generated by Django 5.0.4 on 2024-06-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsre', '0020_img_delete_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='class_fire',
            field=models.FloatField(default=0),
        ),
    ]
